Edit training UI layer
valis-organization/stretchy pull request #52
Opened 2023-09-19 17:22 UTC by DGojka

2023-10-09 10:41 UTC, PPetka requested changes
- [x] I can add empty exercises by clicking "+" multiple times. I also moved an "empty exercise" up, and then I clicked add, the same thing happens. (The easiest way would be to hide an add button, and remove empty exercise if user clicked some other item)
- [x] I can create a training with no exercises (Create training button is shown)
- timeless exercise should be a default when clicking on a "create exercise" button
- after adding an exercise the keyboard is not hiding and covers whole bottom of the screen so I need to close it to add a new exercise
- when removing an exercise (tested on a long list) the view is scrolled to the bottom.
- list elements UI is inconsistent (on the left there are squared elements, on the right are bugged - time element is rounded, but underneeth it there is squared rectangle.
- it is really weird that top bar is blinking when switching between bottom nav bar tabs
I did not even check the code at this point since there are a lot of bugs.

**In a professional environment, adding pull request with so many visual bugs would be consider as a _poor quality work_ and neglection. Probably the people checking that PR would be mad finding so many visual errors without checking the code. Please triple check UI and all the features before adding a PR in the future.**

2023-10-11 11:16 UTC, DGojka commented
> * [ ]  it is really weird that top bar is blinking when switching between bottom nav bar tabs

I don't think this change should be in this PR, so I added the issue here:
 #59

2023-10-11 11:20 UTC, PPetka commented on app/src/main/java/com/example/stretchy/Navigation.kt
> +    when (navBackStackEntry?.destination?.route) {
extract to function

2023-10-11 11:26 UTC, PPetka commented on app/src/main/java/com/example/stretchy/activity/MainActivity.kt
> +                    exit = shrinkVertically(),
- [ ] activity has alot of code, check if there could be a functions to be added
- [ ] extract composables to other files

2023-10-11 11:30 UTC, PPetka commented on app/src/main/java/com/example/stretchy/features/createtraining/ui/CreateOrEditTrainingViewModel.kt
>      private fun isCreateTrainingButtonVisible(
- [ ] check if this can be a view part
- [ ] check why or if the remember has to be a part of a certain composable or can be declared above it.

2023-10-11 11:41 UTC, PPetka commented on app/src/main/java/com/example/stretchy/features/createtraining/ui/composable/buttons/AddOrSubstractButtons.kt
> +fun AddOrSubtractButtons(onTextEntered: (value: Int) -> Unit) {
- [ ] change name to e.g `IncreaseOrDecreaseActivityDurationButtons`

2023-10-11 11:45 UTC, PPetka commented on app/src/main/java/com/example/stretchy/features/createtraining/ui/composable/list/RecyclerView.kt
> +fun RecyclerView(
- [ ] change name to `ActivitList`

2023-10-11 11:46 UTC, PPetka commented on app/src/main/java/com/example/stretchy/features/createtraining/ui/composable/list/RecyclerView.kt
> +private fun getDragAndReorderSimpleItemCallback(adapter: ExerciseListAdapter) =
- [ ] change name to `dragAndDrop...`

2023-10-11 11:47 UTC, PPetka commented on app/src/main/java/com/example/stretchy/features/createtraining/ui/composable/list/RecyclerView.kt
> +private fun getSwipeToDeleteSimpleItemCallback(adapter: ExerciseListAdapter) =
- [ ] remove `get`

2023-10-11 11:48 UTC, PPetka commented on app/src/main/java/com/example/stretchy/features/createtraining/ui/composable/list/listitem/CollapsedItem.kt
> +fun CollapsedItem(
- [ ] change name to `CollapsedActivityItem`

2023-10-11 11:49 UTC, PPetka commented on app/src/main/java/com/example/stretchy/features/createtraining/ui/composable/list/listitem/ExerciseListItem.kt
> +fun ExerciseListItem(
- [ ] change name `ActivityListItem`

2023-10-11 11:50 UTC, PPetka commented on app/src/main/java/com/example/stretchy/features/createtraining/ui/composable/list/listitem/ExpandedItem.kt
> +fun ExpandedItem(
- [ ]  change name`ExpandedActivityListItem`

2023-10-11 11:56 UTC, PPetka commented on app/src/main/java/com/example/stretchy/features/traininglist/ui/TrainingListViewModel.kt
> +    private fun List<Activity>.getExercisesSize(): Int {
-  [ ] `Count` instead of `Size`

2023-10-11 11:56 UTC, PPetka requested changes
few comments

2023-10-12 13:49 UTC, PPetka approved these changes
🎉 🌮 🍕 🎉

2023-10-12 13:49 UTC, merged